### ISSUE TITLE
请问，我每次扫码登录后都出现这种错误怎么办啊?

### ISSUE THREAD

**Issue by yongjie9** [SpectrePrediction/chaoxingautosign#1]
请问，我每次扫码登录后都出现这种错误怎么办啊?
![IMG_20200312_235441](https://user-images.githubusercontent.com/56878302/76542119-83bdb300-64bf-11ea-8526-909daf56c162.jpg)

**Comment by SpectrePrediction** [comment]
是这样的，可以看到获取课程信息是有返回值的（通过了断言)
![截图20200313002809 913](https://user-images.githubusercontent.com/48947643/76543476-87523980-64c1-11ea-9e64-be8fc07110fb.png)
从错误提示中可以看到，course没有得到，定位到178行，或许是有特殊的课程没有相应的信息，如果你有爬虫的基础，你可以选择性的修改此处（判断为空跳过，或者根据具体的情况适配一下），当然，你也可以将__get_all_class_info函数第一句话，也就是__get_class_json函数的返回值打印出来，发送给我（或者你访问__get_class_json中的接口，并将页面截图发送给我也是一样的）（这会让我知道你的课程信息，如果你介意的话）如果我能得到更多信息，我将会在明天或者后天更新它并且完善注释以方便你们修改他，很抱歉我仅仅是做了异常而没有花心思完善这个地方，如果你能完善，请提交更棒的它，很感谢你的提问

**Comment by yongjie9** [comment]
不好意思，我不懂爬虫😂

**Comment by SpectrePrediction** [comment]
😂尝试给我更多信息，例如将__get_class_json函数的返回值打印出来

**Comment by yongjie9** [comment]
我知道为什么出现了，我的课程里面有一科是我自己申请的课（能自己发起签到，为了和我同学实验签到），我用我同学的不会报错，我把我申请的课删除了就不会出现报错了。

**Comment by SpectrePrediction** [comment]
😂很高兴你解决了，目前还是有个小bug在于对已经签到的课签到在有效期内会多次尝试签到，即使第一次签到已经成功，你可以忽视他（不影响使用）也可以修改他，我本以为不会有人发现我的脚本的😊能帮到你们很开心

**Comment by yongjie9** [comment]
谢谢你的脚本
